declare module 'marhevsky/Login';
declare module 'marhevsky/AuthApi';
declare module 'marhevsky/UserApi';
declare module 'marhevsky/TokenUtil';
declare module 'marhevsky/PrivateRoute';
declare module 'marhevsky/Navigation';
declare module 'marhevsky/Home'
declare module 'marhevsky/Category'
declare module 'marhevsky/DragList'
declare module 'marhevsky/Task'
declare module 'marhevsky/AssignTasks'
declare module 'marhevsky/ProjectSimulationReview'
declare module 'marhevsky/Project'
declare module 'marhevsky/Backlog'
declare module 'marhevsky/ProjectOverview'
declare module 'marhevsky/Talent'
declare module 'marhevsky/Worker'
declare module 'marhevsky/jwtApi'
declare module 'marhevsky/Logout'
declare module 'balaz/Home';
declare module 'balaz/AuthService';
declare module 'balaz/UserService';
declare module 'balaz/ProjectList';
declare module 'balaz/Login';
declare module 'balaz/Register';
declare module 'balaz/Project'
declare module 'balaz/Profile'
declare module 'balaz/Backlog'
declare module 'balaz/IUser'
declare module 'balaz/BoardAdmin'
declare module 'marhevsky/AdminCenter'
declare module 'marhevsky/BacklogList'
declare module 'marhevsky/CategoryList'
declare module 'marhevsky/ProjectList'
declare module 'marhevsky/TalentList'
declare module 'marhevsky/TaskList'
declare module 'marhevsky/UserList'
declare module 'marhevsky/WorkerList'